### ISSUE TITLE
NSFPlay 2.5+ roadmap

### ISSUE THREAD

**Issue by bbbradsmith** [bbbradsmith/nsfplay#7]
- Seeking easier, seek when paused/stopped?
- Sound device selection.
- Bus/stack plugins: NSF validator, other export tools
- Improve loop detection
- APU debug pin emulation
- wider resample window? (i.e. multi-lobe sinc?)
- Mac/Linux versions?
- Foobar2000 plugin
- KB plugin
- NSF2
-- https://wiki.nesdev.com/w/index.php/NSF2
-- register poll for "this is NSF2 compliant player"
-- IRQ timer
-- IRQ allowed (just uses current vector)
-- non returning INIT allowed, register to signal "ready" for sound to begin
-- metadata allow NSFe block of chunks to be appended to end
-- register location debate, was it in conflict with discovered test register?
- Visualizer plugin system. Full register view capability.
- De-MFC GUI, change to a .lib, and build directly into plugin.
- Remove plugin stubs from xgm, these belong in the plugin project itself.
- Consider adding a dendy mode to format? maybe save for NSF2?
- Breakout window for info (nice for looking at NSFe text chunk).
- One click button for keyboard view?
- Vertical stacking for multiple key dots on same pitch?
- Other: Infobox song position needs to be synched with true song position on open. (pass, this is a mess)
- Other: Behaviour with 2 NSFs in a playlist is counterintuitive.
- Always On Top > wxSTAY_ON_TOP on wxFrame?

**Comment by bbbradsmith** [comment]
[NSFPlay3](https://github.com/bbbradsmith/nsfplay/tree/nsfplay3) development began in March 2024. Rough milestone goals for first release, this list is a work in progress. Please do not request a timeline.

- [x] Build and CI setup
  - [x] Windows MSVC (32 + 64)
  - [x] Windows MSYS2 (32 + 64)
  - [x] Linux (Ubuntu)
  - [x] MacOS (Intel + ARM)
- [x] Setup library dependencies
  - [x] PortAudio (Cross-platform Audio)
  - [x] WxWidgets (GUI)
- [ ] Core
  - [x] API
    - [x] Playback controls
    - [x] Extensible metadata system
    - [x] Extensible settings system
  - [x] INI file parsing
  - [x] NSF and NSFe file parsing
  - [ ] Playback mechanism
  - [ ] NES CPU emulation
    - [ ] Emulation
    - [ ] Debugging
    - [ ] Logging
  - [ ] Sound Generators
    - [ ] Debug Test
    - [ ] NES APU
    - [ ] FDS
    - [ ] MMC5
    - [ ] Konami VRC6
    - [ ] Konami VRC7
    - [ ] Namco 163
    - [ ] Sunsoft 5B
    - [ ] OneBus VT+
    - [ ] EPSM
  - [ ] Audio resamplers
  - [ ] Audio output filters
  - [ ] Other file type support
    - [ ] BIN
    - [ ] NES
- [ ] Cmd (Command line player/tool)
  - [x] Command line parsing
  - [x] Cross platform interface
  - [ ] Metadata display
  - [ ] Metadata editor
  - [ ] Settings controls
  - [ ] Playback controls
  - [ ] Render to WAV
  - [ ] Unit testing
- [ ] NSFPlay (GUI player)
  - [ ] Property Grid
    - [ ] Settings controls
    - [ ] Metadata display
    - [ ] Metadata editor
  - [ ] Playback controls
  - [ ] Render to WAV
  - [ ] Keyboard view
  - [ ] Debug tools
    - [ ] Memory hex view
    - [ ] Disassembly and trace
    - [ ] Trace logging
- [ ] Winamp plugin
- [ ] Core examples
  - [ ] Sound FX board: loads an NSF and maps tracks to keys.
  - [ ] Lizard BIN music engine demo: play music and integrated sound effects.
  - [ ] No loaded NSF keyboard demo: play tones with keys.
